using SculptFlowAdmin.Entities.Models;

namespace SculptFlowAdmin.Common.Enums;

/// <summary>Allowed values for Message.Origin — must match the CHECK constraint in Database/schema.sql.</summary>
public static class MessageOrigin
{
    /// <summary>Customer message received via the WhatsApp webhook.</summary>
    public const string WhatsAppCustomer = "whatsapp_customer";
    /// <summary>Staff replied directly from the WhatsApp Business phone app (coexistence echo) — never a customer message, never triggers AI.</summary>
    public const string WhatsAppBusinessApp = "whatsapp_business_app";
    /// <summary>Staff replied from our Razor Inbox.</summary>
    public const string Dashboard = "dashboard";
    /// <summary>Generated by the AI agent (via n8n).</summary>
    public const string Ai = "ai";
    /// <summary>Platform-generated (e.g. automated notices), not attributable to a person or the AI.</summary>
    public const string System = "system";
    /// <summary>Sent by an actual Campaign (bulk template send) — a manually-sent template from the
    /// Inbox is still Origin.Dashboard with MessageType "template"; this is reserved for Campaign sends.</summary>
    public const string Campaign = "campaign";
    /// <summary>Customer message received via the Telegram bot webhook.</summary>
    public const string TelegramCustomer = "telegram_customer";

    public static readonly IReadOnlySet<string> All = new HashSet<string>
    {
        WhatsAppCustomer, WhatsAppBusinessApp, Dashboard, Ai, System, Campaign, TelegramCustomer
    };

    /// <summary>The origin of a genuine inbound customer message on the given channel.</summary>
    public static string CustomerFor(string channel) =>
        channel == ConversationChannel.Telegram ? TelegramCustomer : WhatsAppCustomer;
}
